/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import juego.Character;
import juego.AerialFighter;
import juego.Beast;
import juego.ContactFighter;
import juego.Heroes;
import juego.MediumRangeFighter;
import javax.swing.border.LineBorder;

/**
 *
 * @author Diego Álvarez
 */
public class ClassCreator extends javax.swing.JFrame {
    private ArrayList<Character> created = new ArrayList<Character>();
    private Menu menu;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagen","jpg","jpeg","gif");
    /**
     * Creates new form NewJFrame
     */
    public ClassCreator() {
        initComponents();
    }
    public ClassCreator(Menu menu) {
        this.menu = menu;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblArcher = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSpaces1 = new javax.swing.JLabel();
        Spacespinner = new javax.swing.JSpinner();
        HPspinner = new javax.swing.JSpinner();
        lblHP = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblClass = new javax.swing.JLabel();
        ComboBoxClass = new javax.swing.JComboBox<>();
        lblRange = new javax.swing.JLabel();
        txtRange = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblUnlock = new javax.swing.JLabel();
        unlockSpinner = new javax.swing.JSpinner();
        lblDamage = new javax.swing.JLabel();
        damageSpinner = new javax.swing.JSpinner();
        lblNotify = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImgMov = new javax.swing.JLabel();
        btnFileSelectorImgMov = new javax.swing.JButton();
        txtRuteImgMov = new javax.swing.JTextField();
        showImgMov = new javax.swing.JLabel();
        lblImgAtk = new javax.swing.JLabel();
        btnFileSelectorImgAtk1 = new javax.swing.JButton();
        txtRuteImgAtk = new javax.swing.JTextField();
        showImgAtk = new javax.swing.JLabel();
        lblBGpic = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creador de personajes");
        setBackground(new java.awt.Color(102, 255, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/resources/archer.png"))); // NOI18N
        getContentPane().add(lblArcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 330));

        jPanel2.setBackground(new java.awt.Color(255,255,255,100));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 51));

        lblSpaces1.setText("Espacios:");

        Spacespinner.setEditor(new javax.swing.JSpinner.DefaultEditor(Spacespinner));
        Spacespinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        Spacespinner.setAutoscrolls(true);
        Spacespinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        HPspinner.setEditor(new javax.swing.JSpinner.DefaultEditor(HPspinner));
        HPspinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        HPspinner.setAutoscrolls(true);
        HPspinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HPspinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                HPspinnerPropertyChange(evt);
            }
        });

        lblHP.setText("Vida:");

        lblName.setText("Nombre : ");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblClass.setText("Clase : ");

        ComboBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contacto", "Rango", "Aereo", "Besia", "Heroe" }));
        ComboBoxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxClassActionPerformed(evt);
            }
        });

        lblRange.setText("Rango: ");

        txtRange.setEditable(false);
        txtRange.setText("1");
        txtRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRangeActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblUnlock.setText("Desbloqueo:");

        unlockSpinner.setEditor(new javax.swing.JSpinner.DefaultEditor(unlockSpinner));
        unlockSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        unlockSpinner.setToolTipText("");
        unlockSpinner.setAutoscrolls(true);
        unlockSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDamage.setText("Daño: ");

        damageSpinner.setEditor(new javax.swing.JSpinner.DefaultEditor(damageSpinner));
        damageSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        damageSpinner.setToolTipText("");
        damageSpinner.setAutoscrolls(true);
        damageSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblNotify.setForeground(new java.awt.Color(0, 255, 0));

        btnSave.setText("Guardar cambios");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRange)
                                    .addComponent(lblHP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClass)
                                    .addComponent(lblName)
                                    .addComponent(lblUnlock)
                                    .addComponent(lblSpaces1)
                                    .addComponent(lblDamage))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Spacespinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(HPspinner, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(damageSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(unlockSpinner, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HPspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpaces1)
                    .addComponent(Spacespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(damageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDamage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnlock)
                    .addComponent(unlockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lblNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addComponent(btnSave)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 390));

        jPanel3.setBackground(new java.awt.Color(255,255,255,50));
        lblWelcome.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        lblWelcome.setText("   Bienvenido al creador de personajes");
        lblWelcome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblWelcome.setAlignmentY(1.0F);
        lblWelcome.setOpaque(true);
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 320, 30));

        jPanel3.setBackground(new java.awt.Color(255,255,255,100));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 51));

        lblImgMov.setText("Imagen en Movimiento: ");

        btnFileSelectorImgMov.setText("Seleccionar Imagen");
        btnFileSelectorImgMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileSelectorImgMovActionPerformed(evt);
            }
        });

        txtRuteImgMov.setEditable(false);
        txtRuteImgMov.setText("Ruta de imagen");
        txtRuteImgMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuteImgMovActionPerformed(evt);
            }
        });

        showImgMov.setBackground(new java.awt.Color(255, 255, 255,200));
        showImgMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/resources/NULL.png"))); // NOI18N

        lblImgAtk.setText("Imagen de Ataque: ");

        btnFileSelectorImgAtk1.setText("Seleccionar Imagen");
        btnFileSelectorImgAtk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileSelectorImgAtk1ActionPerformed(evt);
            }
        });

        txtRuteImgAtk.setEditable(false);
        txtRuteImgAtk.setText("Ruta de imagen");
        txtRuteImgAtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuteImgAtkActionPerformed(evt);
            }
        });

        showImgAtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/resources/NULLatk.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showImgAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuteImgAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showImgMov, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuteImgMov, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblImgAtk)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFileSelectorImgAtk1))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblImgMov)
                            .addGap(36, 36, 36)
                            .addComponent(btnFileSelectorImgMov))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImgMov)
                    .addComponent(btnFileSelectorImgMov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRuteImgMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showImgMov, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImgAtk)
                    .addComponent(btnFileSelectorImgAtk1))
                .addGap(10, 10, 10)
                .addComponent(txtRuteImgAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showImgAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 350, 390));

        lblBGpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/resources/BGCreateCarac.jpg"))); // NOI18N
        getContentPane().add(lblBGpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void ComboBoxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxClassActionPerformed
        // TODO add your handling code here:
        int selection = ComboBoxClass.getSelectedIndex();
        switch (selection) {
            case 1:
                txtRange.setText("5");
                break;
            case 2:
                txtRange.setText("10");
                break;
            default:
                txtRange.setText("1"); 
                break;
        }
    }//GEN-LAST:event_ComboBoxClassActionPerformed

    private void txtRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRangeActionPerformed

    private void HPspinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_HPspinnerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_HPspinnerPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void cleanAll(){
        HPspinner.setValue(1);
        Spacespinner.setValue(1);
        unlockSpinner.setValue(1);
        damageSpinner.setValue(1);
        ComboBoxClass.setSelectedIndex(0);
        txtRange.setText("1");
        txtName.setText("");
    }
    private Character addCharacter(String name,String imgM, String imgA,int healthPoints,int damage,int spaces,int unlockLvl){
    int selection = ComboBoxClass.getSelectedIndex();
    switch (selection) {
            case 0:
                ContactFighter contact = new ContactFighter(name, imgM,imgA, healthPoints, damage, spaces, 1, unlockLvl);
                return contact;
            case 1:
                MediumRangeFighter range = new MediumRangeFighter(name, imgM,imgA, healthPoints, damage, spaces, 5, unlockLvl);
                return range;
            case 2:
                AerialFighter aerial = new AerialFighter(name, imgM,imgA, healthPoints, damage, spaces, 10, unlockLvl);
                return aerial;
            case 3:
                Beast beastFighter = new Beast(name, imgM,imgA, healthPoints, damage, spaces, 1, unlockLvl);
                return beastFighter;
            case 4:
                Heroes hero = new Heroes(name, imgM,imgA, healthPoints, damage, spaces, 1, unlockLvl);
                return hero;

        }
     return null;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        int healthPoints = (Integer)HPspinner.getValue();
        int spaces = (Integer)Spacespinner.getValue();
        int unlockLvl = (Integer)unlockSpinner.getValue();
        int damage = (Integer)damageSpinner.getValue();
        String imgM  = txtRuteImgMov.getText();
        String imgA  = txtRuteImgAtk.getText();
        created.add(addCharacter(name,imgM,imgA,healthPoints,damage,spaces,unlockLvl));
        cleanAll();
        lblNotify.setText(name+" creado con éxito");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFileSelectorImgAtk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileSelectorImgAtk1ActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();//achu
        selector.setFileFilter(filter);
        int option = selector.showOpenDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            txtRuteImgAtk.setText(selector.getSelectedFile().getPath());
            ImageIcon icon = new ImageIcon(txtRuteImgAtk.getText());
            int width = 90;
            int height = 90;
            icon.setImage(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
            showImgAtk.setIcon(icon);
        }

    }//GEN-LAST:event_btnFileSelectorImgAtk1ActionPerformed

    private void txtRuteImgAtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuteImgAtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuteImgAtkActionPerformed

    private void txtRuteImgMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuteImgMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuteImgMovActionPerformed

    private void btnFileSelectorImgMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileSelectorImgMovActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();//achu
        selector.setFileFilter(filter);
        int option = selector.showOpenDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            txtRuteImgMov.setText(selector.getSelectedFile().getPath());
            ImageIcon icon = new ImageIcon(txtRuteImgMov.getText());
            int width = 90;
            int height = 90;
            icon.setImage(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
            showImgMov.setIcon(icon);
        }

    }//GEN-LAST:event_btnFileSelectorImgMovActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ClassCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxClass;
    private javax.swing.JSpinner HPspinner;
    private javax.swing.JSpinner Spacespinner;
    private javax.swing.JButton btnFileSelectorImgAtk1;
    private javax.swing.JButton btnFileSelectorImgMov;
    private javax.swing.JButton btnSave;
    private javax.swing.JSpinner damageSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblArcher;
    private javax.swing.JLabel lblBGpic;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblImgAtk;
    private javax.swing.JLabel lblImgMov;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNotify;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblSpaces1;
    private javax.swing.JLabel lblUnlock;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel showImgAtk;
    private javax.swing.JLabel showImgMov;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRange;
    private javax.swing.JTextField txtRuteImgAtk;
    private javax.swing.JTextField txtRuteImgMov;
    private javax.swing.JSpinner unlockSpinner;
    // End of variables declaration//GEN-END:variables
}
