/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
/**
 *
 * @author Alejandra G
 */
public class Menu extends javax.swing.JFrame {
    LogIn log = new LogIn(this);
    boolean first = true;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntStart = new javax.swing.JButton();
        bntLoadGame = new javax.swing.JButton();
        bntNewCarac = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntStart.setBackground(new java.awt.Color(100, 135, 0));
        bntStart.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bntStart.setForeground(new java.awt.Color(255, 255, 255));
        bntStart.setText("Iniciar Partida");
        bntStart.setBorder(null);
        bntStart.setBorderPainted(false);
        bntStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntStart.setDefaultCapable(false);
        bntStart.setFocusPainted(false);
        bntStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntStartActionPerformed(evt);
            }
        });
        getContentPane().add(bntStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 130, 50));

        bntLoadGame.setBackground(new java.awt.Color(100, 135, 0));
        bntLoadGame.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bntLoadGame.setForeground(new java.awt.Color(255, 255, 255));
        bntLoadGame.setText("Cargar  Partida");
        bntLoadGame.setBorder(null);
        bntLoadGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntLoadGame.setFocusPainted(false);
        bntLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(bntLoadGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, 50));

        bntNewCarac.setBackground(new java.awt.Color(100, 135, 0));
        bntNewCarac.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bntNewCarac.setForeground(new java.awt.Color(255, 255, 255));
        bntNewCarac.setText("Crear Personaje");
        bntNewCarac.setBorder(null);
        bntNewCarac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntNewCarac.setFocusPainted(false);
        bntNewCarac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNewCaracActionPerformed(evt);
            }
        });
        getContentPane().add(bntNewCarac, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/resources/BGMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntStartActionPerformed

    private void bntLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLoadGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntLoadGameActionPerformed

    private void bntNewCaracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNewCaracActionPerformed
        // TODO add your handling code here: 
        this.setVisible(false);
        log.setVisible(true);
    }//GEN-LAST:event_bntNewCaracActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLoadGame;
    private javax.swing.JButton bntNewCarac;
    private javax.swing.JButton bntStart;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
